version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  my-executor:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

jobs:
  install-dependencies:
    executor: my-executor

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  build-test:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: build
          command: |
            export ENV=test
            export REACT_APP_HN_API_URL=${REACT_APP_HN_API_URL_STAGING}
            yarn build

      - run:
          name: Run the application
          commad: |
            yarn start

      - run:
          name: test
          commad: |
            yarn test

  build-deploy-staging:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: build
          command: |
            export ENV=staging
            export REACT_APP_HN_API_URL=${REACT_APP_HN_API_URL_STAGING}
            yarn build

      - aws-s3/sync:
          from: build
          to: 's3://staging.singleview.hackney.gov.uk/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

  build-deploy-production:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: build
          command: |
            export ENV=production
            export REACT_APP_HN_API_URL=${REACT_APP_HN_API_URL_PRODUCTION}
            yarn build

      - aws-s3/sync:
          from: build
          to: 's3://beta.singleview.hackney.gov.uk/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - install-dependencies
      - build-test:
          requires:
            - install-dependencies
      - build-deploy-staging:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - permit-deploy-production:
          type: approval
          requires:
            - build-deploy-staging
      - build-deploy-production:
          requires:
            - permit-deploy-production
